version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: weekly
    rebase-strategy: disabled
    ignore:
      - dependency-name: '@babel/*'
        versions:
          - '>= 8'
      - dependency-name: '@types/node'
        versions:
          - '>= 25'
      - dependency-name: eslint
        versions:
          - '>= 10.0.0'
    groups:
      babel:
        patterns:
          - '@babel/*'
          - 'babel-*'
          - 'browserslist'
      eslint:
        patterns:
          - '@eslint-*'
          - '@eslint/*'
          - 'eslint-*'
          - 'eslint'
      jest:
        patterns:
          - '@jest/'
          - 'jest-*'
          - 'jest'
          - '@types/jest'
      laboperator-gmbh:
        patterns:
          - '@laboperator-gmbh/*'
